// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf8EcrO0CXf79r63TjH8n9utxvtjWSw6k',
    appId: '1:845946524476:web:3c27529e35cf9f797c0439',
    messagingSenderId: '845946524476',
    projectId: 'dream-journal-cb3fb',
    authDomain: 'dream-journal-cb3fb.firebaseapp.com',
    storageBucket: 'dream-journal-cb3fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBL6tRq4bnryAvaE57aTfAmkJ1tzqU_NE',
    appId: '1:845946524476:android:032cd14cc5a7bbaf7c0439',
    messagingSenderId: '845946524476',
    projectId: 'dream-journal-cb3fb',
    storageBucket: 'dream-journal-cb3fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_kXQrfNNmgkQR_2UW23LtKvohjDpbb4',
    appId: '1:845946524476:ios:9900510421a76a4a7c0439',
    messagingSenderId: '845946524476',
    projectId: 'dream-journal-cb3fb',
    storageBucket: 'dream-journal-cb3fb.firebasestorage.app',
    iosBundleId: 'com.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_kXQrfNNmgkQR_2UW23LtKvohjDpbb4',
    appId: '1:845946524476:ios:44041c7a05abb07f7c0439',
    messagingSenderId: '845946524476',
    projectId: 'dream-journal-cb3fb',
    storageBucket: 'dream-journal-cb3fb.firebasestorage.app',
    iosBundleId: 'com.ex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf8EcrO0CXf79r63TjH8n9utxvtjWSw6k',
    appId: '1:845946524476:web:5a97703439798ae97c0439',
    messagingSenderId: '845946524476',
    projectId: 'dream-journal-cb3fb',
    authDomain: 'dream-journal-cb3fb.firebaseapp.com',
    storageBucket: 'dream-journal-cb3fb.firebasestorage.app',
  );
}
